import type { ModelConfig } from '../../model/types';

// Buoy model.
// Data generated by: tsx scripts/generate/buoy.ts
// (or use the procedural generator and compile in one step — TBD)
export default {
  materialOverrides: { buoy: { color: 0xff4422, roughness: 0.6, metalness: 0 } },
} satisfies ModelConfig;
