// Auto-generated by scripts/sync-resources.mjs — do not edit manually
// Resolution: 4k, Format: jpg

export interface TextureSet {
  diff: string;
  nor_gl?: string;
  rough?: string;
  metal?: string;
  ao?: string;
  disp?: string;
  alpha?: string;
  wrapS?: number;
  wrapT?: number;
}

export const TEXTURES: Record<string, TextureSet> = {
  'ccivHull': {
    diff: '/textures/ship_pinnace/hull/diff_4k.jpg',
    nor_gl: '/textures/ship_pinnace/hull/nor_gl_4k.jpg',
    rough: '/textures/ship_pinnace/hull/rough_4k.jpg',
    metal: '/textures/ship_pinnace/hull/metal_4k.jpg',
    wrapS: 2,
    wrapT: 3
  },
  'ccivDeck': {
    diff: '/textures/ship_pinnace/deck/diff_4k.jpg',
    nor_gl: '/textures/ship_pinnace/deck/nor_gl_4k.jpg',
    rough: '/textures/ship_pinnace/deck/rough_4k.jpg',
    wrapS: 3.5,
    wrapT: 9
  },
  'ccivSail': {
    diff: '/textures/ship_pinnace/sails/diff_4k.jpg',
    nor_gl: '/textures/ship_pinnace/sails/nor_gl_4k.jpg',
    rough: '/textures/ship_pinnace/sails/rough_4k.jpg',
    metal: '/textures/ship_pinnace/sails/metal_4k.jpg',
    alpha: '/textures/ship_pinnace/sails/alpha_4k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'ccivRigging': {
    diff: '/textures/ship_pinnace/rigging/diff_4k.jpg',
    nor_gl: '/textures/ship_pinnace/rigging/nor_gl_4k.jpg',
    rough: '/textures/ship_pinnace/rigging/rough_4k.jpg',
    metal: '/textures/ship_pinnace/rigging/metal_4k.jpg',
    wrapS: 1,
    wrapT: 2
  },
  'ccivAft': {
    diff: '/textures/ship_pinnace/aft/diff_4k.jpg',
    nor_gl: '/textures/ship_pinnace/aft/nor_gl_4k.jpg',
    rough: '/textures/ship_pinnace/aft/rough_4k.jpg',
    metal: '/textures/ship_pinnace/aft/metal_4k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'ccivDetails': {
    diff: '/textures/ship_pinnace/details/diff_4k.jpg',
    nor_gl: '/textures/ship_pinnace/details/nor_gl_4k.jpg',
    rough: '/textures/ship_pinnace/details/rough_4k.jpg',
    metal: '/textures/ship_pinnace/details/metal_4k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'ccivInterior': {
    diff: '/textures/ship_pinnace/interior/diff_4k.jpg',
    nor_gl: '/textures/ship_pinnace/interior/nor_gl_4k.jpg',
    rough: '/textures/ship_pinnace/interior/rough_4k.jpg',
    wrapS: 1,
    wrapT: 1
  },
};
