// Auto-generated by scripts/fetch-textures.mjs — do not edit manually
// Resolution: 2k, Format: jpg

export interface TextureSet {
  diff: string;
  nor_gl?: string;
  rough?: string;
  metal?: string;
  ao?: string;
  disp?: string;
  wrapS?: number;
  wrapT?: number;
}

export const TEXTURES: Record<string, TextureSet> = {
  'mast': {
    diff: '/textures/oak_veneer_01/oak_veneer_01_diff_2k.jpg',
    nor_gl: '/textures/oak_veneer_01/oak_veneer_01_nor_gl_2k.jpg',
    rough: '/textures/oak_veneer_01/oak_veneer_01_rough_2k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'hull': {
    diff: '/textures/fine_grained_wood/fine_grained_wood_diff_2k.jpg',
    nor_gl: '/textures/fine_grained_wood/fine_grained_wood_nor_gl_2k.jpg',
    rough: '/textures/fine_grained_wood/fine_grained_wood_rough_2k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'deck': {
    diff: '/textures/wood_planks/wood_planks_diff_2k.jpg',
    nor_gl: '/textures/wood_planks/wood_planks_nor_gl_2k.jpg',
    rough: '/textures/wood_planks/wood_planks_rough_2k.jpg',
    ao: '/textures/wood_planks/wood_planks_ao_2k.jpg',
    wrapS: 3.5,
    wrapT: 9
  },
  'sail': {
    diff: '/textures/hessian_380/hessian_380_diff_2k.jpg',
    nor_gl: '/textures/hessian_380/hessian_380_nor_gl_2k.jpg',
    rough: '/textures/hessian_380/hessian_380_rough_2k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'iron': {
    diff: '/textures/corrugated_iron/corrugated_iron_diff_2k.jpg',
    nor_gl: '/textures/corrugated_iron/corrugated_iron_nor_gl_2k.jpg',
    rough: '/textures/corrugated_iron/corrugated_iron_rough_2k.jpg',
    metal: '/textures/corrugated_iron/corrugated_iron_metal_2k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'copper': {
    diff: '/textures/rusty_metal_grid/rusty_metal_grid_diff_2k.jpg',
    nor_gl: '/textures/rusty_metal_grid/rusty_metal_grid_nor_gl_2k.jpg',
    rough: '/textures/rusty_metal_grid/rusty_metal_grid_rough_2k.jpg',
    wrapS: 3.5,
    wrapT: 1
  },
  'leather': {
    diff: '/textures/brown_leather/brown_leather_diff_2k.jpg',
    nor_gl: '/textures/brown_leather/brown_leather_nor_gl_2k.jpg',
    rough: '/textures/brown_leather/brown_leather_rough_2k.jpg',
    ao: '/textures/brown_leather/brown_leather_ao_2k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'pinnaceHull': {
    diff: '/textures/ship_pinnace/ship_pinnace_hull_diff_2k.jpg',
    nor_gl: '/textures/ship_pinnace/ship_pinnace_hull_nor_gl_2k.jpg',
    rough: '/textures/ship_pinnace/ship_pinnace_hull_rough_2k.jpg',
    metal: '/textures/ship_pinnace/ship_pinnace_hull_metal_2k.jpg',
    wrapS: 2,
    wrapT: 3
  },
  'pinnaceDeck': {
    diff: '/textures/ship_pinnace/ship_pinnace_deck_diff_2k.jpg',
    nor_gl: '/textures/ship_pinnace/ship_pinnace_deck_nor_gl_2k.jpg',
    rough: '/textures/ship_pinnace/ship_pinnace_deck_rough_2k.jpg',
    metal: '/textures/ship_pinnace/ship_pinnace_deck_metal_2k.jpg',
    wrapS: 3.5,
    wrapT: 9
  },
  'pinnaceSail': {
    diff: '/textures/ship_pinnace/ship_pinnace_sails_diff_2k.jpg',
    nor_gl: '/textures/ship_pinnace/ship_pinnace_sails_nor_gl_2k.jpg',
    rough: '/textures/ship_pinnace/ship_pinnace_sails_rough_2k.jpg',
    metal: '/textures/ship_pinnace/ship_pinnace_sails_metal_2k.jpg',
    wrapS: 1,
    wrapT: 1
  },
  'pinnaceRigging': {
    diff: '/textures/ship_pinnace/ship_pinnace_rigging_diff_2k.jpg',
    nor_gl: '/textures/ship_pinnace/ship_pinnace_rigging_nor_gl_2k.jpg',
    rough: '/textures/ship_pinnace/ship_pinnace_rigging_rough_2k.jpg',
    metal: '/textures/ship_pinnace/ship_pinnace_rigging_metal_2k.jpg',
    wrapS: 1,
    wrapT: 2
  },
};
