// Auto-generated by scripts/build-model.mjs — do not edit manually
// Model textures — paths relative to public/

export interface TextureSet {
  diff?: string;
  nor_gl?: string;
  rough?: string;
  metal?: string;
  arm?: string;
  alpha?: string;
}

export const TEXTURES: Record<string, TextureSet> = {
  'ccivHull': {
  diff: '/textures/ship/hull/diff_4k.jpg',
  metal: '/textures/ship/hull/metal_4k.jpg',
  nor_gl: '/textures/ship/hull/nor_gl_4k.jpg',
  rough: '/textures/ship/hull/rough_4k.jpg'
  },
  'ccivDeck': {
  diff: '/textures/ship/deck/diff_4k.jpg',
  nor_gl: '/textures/ship/deck/nor_gl_4k.jpg',
  rough: '/textures/ship/deck/rough_4k.jpg'
  },
  'ccivSail': {
  alpha: '/textures/ship/sails/alpha_4k.jpg',
  diff: '/textures/ship/sails/diff_4k.jpg',
  metal: '/textures/ship/sails/metal_4k.jpg',
  nor_gl: '/textures/ship/sails/nor_gl_4k.jpg',
  rough: '/textures/ship/sails/rough_4k.jpg'
  },
  'ccivAft': {
  diff: '/textures/ship/aft/diff_4k.jpg',
  metal: '/textures/ship/aft/metal_4k.jpg',
  nor_gl: '/textures/ship/aft/nor_gl_4k.jpg',
  rough: '/textures/ship/aft/rough_4k.jpg'
  },
  'ccivRigging': {
  diff: '/textures/ship/rigging/diff_4k.jpg',
  metal: '/textures/ship/rigging/metal_4k.jpg',
  nor_gl: '/textures/ship/rigging/nor_gl_4k.jpg',
  rough: '/textures/ship/rigging/rough_4k.jpg'
  },
  'ccivDetails': {
  diff: '/textures/ship/details/diff_4k.jpg',
  metal: '/textures/ship/details/metal_4k.jpg',
  nor_gl: '/textures/ship/details/nor_gl_4k.jpg',
  rough: '/textures/ship/details/rough_4k.jpg'
  },
  'ccivInterior': {
  diff: '/textures/ship/interior/diff_4k.jpg',
  nor_gl: '/textures/ship/interior/nor_gl_4k.jpg',
  rough: '/textures/ship/interior/rough_4k.jpg'
  },
};
