// Auto-generated by scripts/extract-cciv.mjs
// Source: Poly Haven cciv (CC0)
export interface MeshData {
  pos: Float32Array;
  nml: Float32Array;
  uv: Float32Array;
  indices: Uint16Array | Uint32Array;
  hasUV2?: boolean;
  uv2?: Float32Array;
}
import { aft_pos } from './aft_pos.js';
import { aft_uv } from './aft_uv.js';
import { aft_uv2 } from './aft_uv2.js';
import { aft_nml } from './aft_nml.js';
import { aft_idx } from './aft_idx.js';
export const aft: MeshData = {
  pos: aft_pos,
  uv: aft_uv,
  uv2: aft_uv2,
  nml: aft_nml,
  indices: aft_idx,
  hasUV2: true,
};

import { rigging_pos } from './rigging_pos.js';
import { rigging_uv } from './rigging_uv.js';
import { rigging_nml } from './rigging_nml.js';
import { rigging_idx } from './rigging_idx.js';
export const rigging: MeshData = {
  pos: rigging_pos,
  uv: rigging_uv,
  nml: rigging_nml,
  indices: rigging_idx,
};

import { details_pos } from './details_pos.js';
import { details_uv } from './details_uv.js';
import { details_nml } from './details_nml.js';
import { details_idx } from './details_idx.js';
export const details: MeshData = {
  pos: details_pos,
  uv: details_uv,
  nml: details_nml,
  indices: details_idx,
};

import { hull_pos } from './hull_pos.js';
import { hull_uv } from './hull_uv.js';
import { hull_nml } from './hull_nml.js';
import { hull_idx } from './hull_idx.js';
export const hull: MeshData = {
  pos: hull_pos,
  uv: hull_uv,
  nml: hull_nml,
  indices: hull_idx,
};

import { deck_pos } from './deck_pos.js';
import { deck_uv } from './deck_uv.js';
import { deck_nml } from './deck_nml.js';
import { deck_idx } from './deck_idx.js';
export const deck: MeshData = {
  pos: deck_pos,
  uv: deck_uv,
  nml: deck_nml,
  indices: deck_idx,
};

import { interior_pos } from './interior_pos.js';
import { interior_uv } from './interior_uv.js';
import { interior_nml } from './interior_nml.js';
import { interior_idx } from './interior_idx.js';
export const interior: MeshData = {
  pos: interior_pos,
  uv: interior_uv,
  nml: interior_nml,
  indices: interior_idx,
};

import { sails_pos } from './sails_pos.js';
import { sails_uv } from './sails_uv.js';
import { sails_nml } from './sails_nml.js';
import { sails_idx } from './sails_idx.js';
export const sails: MeshData = {
  pos: sails_pos,
  uv: sails_uv,
  nml: sails_nml,
  indices: sails_idx,
};

export const MODEL_INFO = {
  name: 'cciv',
  source: 'https://polyhaven.com/a/cciv',
  license: 'CC0',
  polyCount: 168317,
};

import * as THREE from 'three';

export function buildCCIVGeometry(name: string): THREE.BufferGeometry {
  const data: MeshData = {
    'aft': aft,
    'rigging': rigging,
    'details': details,
    'hull': hull,
    'deck': deck,
    'interior': interior,
    'sails': sails
  }[name] as MeshData;
  if (!data) throw new Error('Unknown cciv mesh: ' + name);

  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.BufferAttribute(data.pos, 3));
  g.setAttribute('normal', new THREE.BufferAttribute(data.nml, 3));
  g.setAttribute('uv', new THREE.BufferAttribute(data.uv, 2));
  if (data.hasUV2 && data.uv2) {
    g.setAttribute('uv2', new THREE.BufferAttribute(data.uv2, 2));
  }
  g.setIndex(new THREE.BufferAttribute(data.indices, 1));
  return g;
}
