// Model: ship
// Built from reference: ship_pinnace
// Auto-generated by scripts/build-model.mjs
export interface MeshData {
  pos: Float32Array;
  nml: Float32Array;
  uv: Float32Array;
  indices: Uint16Array | Uint32Array;
  hasUV2?: boolean;
  uv2?: Float32Array;
}
import { hull_pos } from './data/hull/pos.js';
import { hull_uv } from './data/hull/uv.js';
import { hull_nml } from './data/hull/nml.js';
import { hull_idx } from './data/hull/idx.js';
export const hull: MeshData = {
  pos: hull_pos,
  uv: hull_uv,
  nml: hull_nml,
  indices: hull_idx,
};
import { deck_pos } from './data/deck/pos.js';
import { deck_uv } from './data/deck/uv.js';
import { deck_nml } from './data/deck/nml.js';
import { deck_idx } from './data/deck/idx.js';
export const deck: MeshData = {
  pos: deck_pos,
  uv: deck_uv,
  nml: deck_nml,
  indices: deck_idx,
};
import { sails_pos } from './data/sails/pos.js';
import { sails_uv } from './data/sails/uv.js';
import { sails_nml } from './data/sails/nml.js';
import { sails_idx } from './data/sails/idx.js';
export const sails: MeshData = {
  pos: sails_pos,
  uv: sails_uv,
  nml: sails_nml,
  indices: sails_idx,
};
import { aft_pos } from './data/aft/pos.js';
import { aft_uv } from './data/aft/uv.js';
import { aft_nml } from './data/aft/nml.js';
import { aft_idx } from './data/aft/idx.js';
import { aft_uv2 } from './data/aft/uv2.js';
export const aft: MeshData = {
  pos: aft_pos,
  uv: aft_uv,
  nml: aft_nml,
  indices: aft_idx,
  uv2: aft_uv2,
};
import { rigging_pos } from './data/rigging/pos.js';
import { rigging_uv } from './data/rigging/uv.js';
import { rigging_nml } from './data/rigging/nml.js';
import { rigging_idx } from './data/rigging/idx.js';
export const rigging: MeshData = {
  pos: rigging_pos,
  uv: rigging_uv,
  nml: rigging_nml,
  indices: rigging_idx,
};
import { details_pos } from './data/details/pos.js';
import { details_uv } from './data/details/uv.js';
import { details_nml } from './data/details/nml.js';
import { details_idx } from './data/details/idx.js';
export const details: MeshData = {
  pos: details_pos,
  uv: details_uv,
  nml: details_nml,
  indices: details_idx,
};
import { interior_pos } from './data/interior/pos.js';
import { interior_uv } from './data/interior/uv.js';
import { interior_nml } from './data/interior/nml.js';
import { interior_idx } from './data/interior/idx.js';
export const interior: MeshData = {
  pos: interior_pos,
  uv: interior_uv,
  nml: interior_nml,
  indices: interior_idx,
};

export const MODEL_INFO = {
  name: 'ship',
  source: 'Reference: ship_pinnace',
  license: 'CC0',
  polyCount: 168317,
};