// Auto-generated by scripts/sync-resources.mjs
// Source: Poly Haven ship_pinnace (CC0)
export interface MeshData {
  pos: Float32Array;
  nml: Float32Array;
  uv: Float32Array;
  indices: Uint16Array | Uint32Array;
  hasUV2?: boolean;
  uv2?: Float32Array;
}
import { aft_pos } from './data/aft_pos.js';
import { aft_uv } from './data/aft_uv.js';
import { aft_uv2 } from './data/aft_uv2.js';
import { aft_nml } from './data/aft_nml.js';
import { aft_idx } from './data/aft_idx.js';
export const aft: MeshData = {
  pos: aft_pos,
  uv: aft_uv,
  uv2: aft_uv2,
  nml: aft_nml,
  indices: aft_idx,
  hasUV2: true,
};
import { rigging_pos } from './data/rigging_pos.js';
import { rigging_uv } from './data/rigging_uv.js';
import { rigging_nml } from './data/rigging_nml.js';
import { rigging_idx } from './data/rigging_idx.js';
export const rigging: MeshData = {
  pos: rigging_pos,
  uv: rigging_uv,
  nml: rigging_nml,
  indices: rigging_idx,
};
import { details_pos } from './data/details_pos.js';
import { details_uv } from './data/details_uv.js';
import { details_nml } from './data/details_nml.js';
import { details_idx } from './data/details_idx.js';
export const details: MeshData = {
  pos: details_pos,
  uv: details_uv,
  nml: details_nml,
  indices: details_idx,
};
import { hull_pos } from './data/hull_pos.js';
import { hull_uv } from './data/hull_uv.js';
import { hull_nml } from './data/hull_nml.js';
import { hull_idx } from './data/hull_idx.js';
export const hull: MeshData = {
  pos: hull_pos,
  uv: hull_uv,
  nml: hull_nml,
  indices: hull_idx,
};
import { deck_pos } from './data/deck_pos.js';
import { deck_uv } from './data/deck_uv.js';
import { deck_nml } from './data/deck_nml.js';
import { deck_idx } from './data/deck_idx.js';
export const deck: MeshData = {
  pos: deck_pos,
  uv: deck_uv,
  nml: deck_nml,
  indices: deck_idx,
};
import { interior_pos } from './data/interior_pos.js';
import { interior_uv } from './data/interior_uv.js';
import { interior_nml } from './data/interior_nml.js';
import { interior_idx } from './data/interior_idx.js';
export const interior: MeshData = {
  pos: interior_pos,
  uv: interior_uv,
  nml: interior_nml,
  indices: interior_idx,
};
import { sails_pos } from './data/sails_pos.js';
import { sails_uv } from './data/sails_uv.js';
import { sails_nml } from './data/sails_nml.js';
import { sails_idx } from './data/sails_idx.js';
export const sails: MeshData = {
  pos: sails_pos,
  uv: sails_uv,
  nml: sails_nml,
  indices: sails_idx,
};

export const MODEL_INFO = {
  name: 'ship',
  source: 'https://polyhaven.com/a/ship_pinnace',
  license: 'CC0',
  polyCount: 168317,
};