#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync, copyFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const REFS_DIR = join(ROOT, '.cache', 'references');

const THREE_CONST = { DoubleSide: 2, BackSide: 1, FrontSide: 0 };
const SOURCES_PATH = join(ROOT, 'src', 'textures', 'sources.ts');

const MAP_SUFFIX = {
  diff: 'diff', nor_gl: 'nor_gl', nor_dx: 'nor_dx', rough: 'rough',
  metal: 'metal', arm: 'arm', alpha: 'alpha', disp: 'disp', ao: 'ao',
};

async function buildModel(modelName, modelCfg) {
  const texEntries = [];
  const { source, groups, transform } = modelCfg;
  const refDir = join(REFS_DIR, source);

  if (!existsSync(refDir)) {
    console.error(`  Reference '${source}' not found. Run 'node scripts/pull-reference.mjs' first.`);
    return;
  }

  const outDir = join(ROOT, 'src', 'models', modelName);
  const dataDir = join(outDir, 'data');
  const texDir = join(ROOT, 'public', 'textures', modelName);

  // Wipe previous build so only our files remain
  if (existsSync(outDir)) rmSync(outDir, { recursive: true });
  mkdirSync(dataDir, { recursive: true });
  mkdirSync(texDir, { recursive: true });

  // Read reference index to know what mesh data exists
  const refIndex = readFileSync(join(refDir, 'index.ts'), 'utf-8');

  const indexTsLines = [
    `// Model: ${modelName}`,
    `// Built from reference: ${source}`,
    `// Auto-generated by scripts/build-model.mjs`,
    `export interface MeshData {`,
    `  pos: Float32Array;`,
    `  nml: Float32Array;`,
    `  uv: Float32Array;`,
    `  indices: Uint16Array | Uint32Array;`,
    `  hasUV2?: boolean;`,
    `  uv2?: Float32Array;`,
    `}`,
  ];

  const configGroupEntries = [];
  let polyCount = 0;

  for (const [ourName, groupCfg] of Object.entries(groups)) {
    const refMeshName = groupCfg.mesh;
    const groupDir = join(dataDir, ourName);
    mkdirSync(groupDir, { recursive: true });

    // Copy and rename data files from reference into group subdirectory
    const refDataDir = join(REFS_DIR, source, 'data');
    const refFiles = readdirSync(refDataDir);
    const refPrefix = `${source}_${refMeshName}`;
    const attrMap = { pos: 'pos', nml: 'nml', uv: 'uv', uv2: 'uv2' };

    for (const file of refFiles) {
      if (!file.startsWith(refPrefix)) continue;
      const attrKey = file.replace(`${refPrefix}_`, '').replace('.js', '');
      let content = readFileSync(join(refDataDir, file), 'utf-8');
      content = content.replace(new RegExp(`\\b${refPrefix}_(?=\\w)`, 'g'), `${ourName}_`);
      writeFileSync(join(groupDir, `${attrKey}.js`), content);
    }

    // Count poly count from index data
    const idxContent = readFileSync(join(groupDir, 'idx.js'), 'utf-8');
    const match = idxContent.match(/new Uint(?:16|32)Array\(\[([\s\S]*?)\]\)/);
    if (match) {
      const values = match[1].split(',').filter(s => s.trim());
      polyCount += values.length / 3;
    }

    // Add to index.ts
    const hasUV2 = existsSync(join(groupDir, 'uv2.js'));
    indexTsLines.push(`import { ${ourName}_pos } from './data/${ourName}/pos.js';`);
    indexTsLines.push(`import { ${ourName}_uv } from './data/${ourName}/uv.js';`);
    indexTsLines.push(`import { ${ourName}_nml } from './data/${ourName}/nml.js';`);
    indexTsLines.push(`import { ${ourName}_idx } from './data/${ourName}/idx.js';`);
    if (hasUV2) indexTsLines.push(`import { ${ourName}_uv2 } from './data/${ourName}/uv2.js';`);

    indexTsLines.push(`export const ${ourName}: MeshData = {`);
    indexTsLines.push(`  pos: ${ourName}_pos,`);
    indexTsLines.push(`  uv: ${ourName}_uv,`);
    indexTsLines.push(`  nml: ${ourName}_nml,`);
    indexTsLines.push(`  indices: ${ourName}_idx,`);
    if (hasUV2) indexTsLines.push(`  uv2: ${ourName}_uv2,`);
    indexTsLines.push(`};`);

    configGroupEntries.push(`    { name: '${ourName}', type: 'extracted',`);
    configGroupEntries.push(`      pos: ${ourName}.pos,`);
    configGroupEntries.push(`      uv: ${ourName}.uv,`);
    configGroupEntries.push(`      nml: ${ourName}.nml,`);
    configGroupEntries.push(`      indices: ${ourName}.indices,`);
    if (hasUV2) configGroupEntries.push(`      uv2: ${ourName}.uv2,`);
    configGroupEntries.push(`      textureKey: '${groupCfg.texture}',`);
    configGroupEntries.push(`    },`);

    // Copy textures from reference → public/textures/<model>/{group}/
    // Rename from API key (hull_diff_4k.jpg) to local key (diff_4k.jpg)
    const refTexDir = join(REFS_DIR, source, 'textures', refMeshName);
    if (existsSync(refTexDir)) {
      const texFiles = readdirSync(refTexDir);
      const groupTexDir = join(texDir, ourName);
      mkdirSync(groupTexDir, { recursive: true });
      const maps = {};
      for (const texFile of texFiles) {
        const localName = texFile.replace(`${refMeshName}_`, '');
        copyFileSync(join(refTexDir, texFile), join(groupTexDir, localName));
        // Detect map type from API key suffix (hull_diff → diff)
        const apiKey = texFile.replace(/_\d+k\..+$/, '');
        const suffix = apiKey.replace(`${refMeshName}_`, '');
        const localKey = Object.entries(MAP_SUFFIX).find(([_, v]) => v === suffix)?.[0] || suffix;
        maps[localKey] = `/textures/${modelName}/${ourName}/${localName}`;
      }
      texEntries.push({ name: groupCfg.texture, maps });
    }
  }

  indexTsLines.push(``);
  indexTsLines.push(`export const MODEL_INFO = {`);
  indexTsLines.push(`  name: '${modelName}',`);
  indexTsLines.push(`  source: 'Reference: ${source}',`);
  indexTsLines.push(`  license: 'CC0',`);
  indexTsLines.push(`  polyCount: ${Math.round(polyCount)},`);
  indexTsLines.push(`};`);

  writeFileSync(join(outDir, 'index.ts'), indexTsLines.join('\n'));

  // Generate config.ts
  const configLines = [
    `// Model: ${modelName}`,
    `// Built from reference: ${source}`,
    `// Auto-generated by scripts/build-model.mjs`,
    `import type { ModelConfig } from '../../model/types';`,
    `import { ${Object.keys(groups).join(', ')} } from './index';`,
    `import * as THREE from 'three';`,
    ``,
    `export const ${modelName}Config: ModelConfig = {`,
    `  id: '${modelName}',`,
    `  source: 'extracted',`,
  ];

  if (transform) {
    if (transform.scale) configLines.push(`  transform: { scale: ${JSON.stringify(transform.scale)} },`);
  }

  configLines.push(`  metadata: {`);
  configLines.push(`    license: 'CC0',`);
  configLines.push(`    sourceUrl: 'Reference: ${source}',`);
  configLines.push(`    polyCount: ${Math.round(polyCount)},`);
  configLines.push(`  },`);
  configLines.push(`  meshGroups: [`);
  configLines.push(configGroupEntries.join('\n'));
  configLines.push(`  ],`);

  // Material overrides
  const overrideEntries = Object.entries(groups).filter(([_, g]) => g.material);
  if (overrideEntries.length > 0) {
    configLines.push(`  materialOverrides: {`);
    for (const [groupName, g] of overrideEntries) {
      const mat = g.material;
      const props = Object.entries(mat).map(([k, v]) => {
        if (typeof v === 'string' && v.startsWith('0x')) return `    ${k}: ${v}`;
        if (k === 'side' && typeof v === 'string' && THREE_CONST[v] !== undefined)
          return `    ${k}: THREE.${v}`;
        return `    ${k}: ${JSON.stringify(v)}`;
      });
      configLines.push(`    ${groupName}: { ${props.join(', ')} },`);
    }
    configLines.push(`  },`);
  }

  configLines.push(`};`);
  writeFileSync(join(outDir, 'config.ts'), configLines.join('\n'));

  console.log(`  Built ${Object.keys(groups).length} mesh groups → src/models/${modelName}/`);
  return texEntries;
}

function generateSources(modelTexEntries) {
  const flat = modelTexEntries.flat();
  if (flat.length === 0) return;
  const lines = [
    `// Auto-generated by scripts/build-model.mjs — do not edit manually`,
    `// Model textures — paths relative to public/`,
    ``,
    `export interface TextureSet {`,
    `  diff?: string;`,
    `  nor_gl?: string;`,
    `  rough?: string;`,
    `  metal?: string;`,
    `  arm?: string;`,
    `  alpha?: string;`,
    `}`,
    ``,
    `export const TEXTURES: Record<string, TextureSet> = {`,
  ];
  for (const { name, maps } of flat) {
    const entries = Object.entries(maps)
      .filter(([k]) => k !== 'nor_dx' && k !== 'disp' && k !== 'arm')
      .map(([k, v]) => `  ${k}: '${v}'`);
    if (entries.length) lines.push(`  '${name}': {\n${entries.join(',\n')}\n  },`);
  }
  lines.push(`};`, ``);
  writeFileSync(SOURCES_PATH, lines.join('\n'));
  console.log(`\nGenerated ${SOURCES_PATH}`);
}

async function main() {
  const models = JSON.parse(readFileSync(join(__dirname, 'models.json'), 'utf-8'));
  console.log('Building models from references → src/models/\n');
  const allTexEntries = [];
  for (const [name, cfg] of Object.entries(models)) {
    console.log(`[${name}]`);
    const entries = await buildModel(name, cfg);
    allTexEntries.push(entries);
  }
  generateSources(allTexEntries);
  console.log('\nDone. Models are owned — edit src/models/<id>/ directly.');
}

main().catch(err => { console.error(err); process.exit(1); });
