#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const GLTF_PATH = '/tmp/cciv_ref/cciv_1k.gltf'
const BIN_PATH = join(ROOT, 'public', 'models', 'cciv', 'cciv.bin');
const OUT_DIR = join(ROOT, 'src', 'ship', 'cciv');

function fmtFloat32(arr) {
  const parts = [];
  for (let i = 0; i < arr.length; i++) {
    if (i > 0 && i % 8 === 0) parts.push('\n  ');
    parts.push(arr[i].toFixed(6));
    if (i < arr.length - 1) parts.push(', ');
  }
  return parts.join('');
}

function fmtUint16(arr) {
  const parts = [];
  for (let i = 0; i < arr.length; i++) {
    if (i > 0 && i % 16 === 0) parts.push('\n  ');
    parts.push(String(arr[i]));
    if (i < arr.length - 1) parts.push(', ');
  }
  return parts.join('');
}

function fmtUint32(arr) {
  const parts = [];
  for (let i = 0; i < arr.length; i++) {
    if (i > 0 && i % 12 === 0) parts.push('\n  ');
    parts.push(String(arr[i]));
    if (i < arr.length - 1) parts.push(', ');
  }
  return parts.join('');
}

const COMP_TYPE = {
  5120: Int8Array,
  5121: Uint8Array,
  5122: Int16Array,
  5123: Uint16Array,
  5124: Int32Array,
  5125: Uint32Array,
  5126: Float32Array,
};

const COMP_SIZE = {
  5120: 1, 5121: 1, 5122: 2, 5123: 2,
  5124: 4, 5125: 4, 5126: 4,
};

const NUM_COMP = { SCALAR: 1, VEC2: 2, VEC3: 3, VEC4: 4 };

function argName(attrKey) {
  const map = { POSITION: 'pos', NORMAL: 'nml', TEXCOORD_0: 'uv', TEXCOORD_1: 'uv2' };
  return map[attrKey] || attrKey.toLowerCase();
}

function main() {
  if (!existsSync(GLTF_PATH)) {
    console.error(`Download the 1k glTF first:\n  curl -sL -o ${GLTF_PATH} "https://dl.polyhaven.org/file/ph-assets/Models/gltf/1k/cciv/cciv_1k.gltf"\n  curl -sL -o ${BIN_PATH} "https://dl.polyhaven.org/file/ph-assets/Models/gltf/1k/cciv/cciv.bin"`);
    process.exit(1);
  }

  const gltf = JSON.parse(readFileSync(GLTF_PATH, 'utf-8'));
  const bin = readFileSync(BIN_PATH);

  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

  const meshes = gltf.meshes;
  const accessors = gltf.accessors;
  const bufferViews = gltf.bufferViews;
  const nodes = gltf.nodes;

  const meshNames = {};

  for (const node of nodes) {
    if (node.mesh !== undefined) {
      const m = meshes[node.mesh];
      meshNames[node.mesh] = node.name.replace(/^cciv_/, '');
    }
  }

  const indexTsLines = [
    `// Auto-generated by scripts/extract-cciv.mjs`,
    `// Source: Poly Haven cciv (CC0)`,
    `export interface MeshData {`,
    `  pos: Float32Array;`,
    `  nml: Float32Array;`,
    `  uv: Float32Array;`,
    `  indices: Uint16Array | Uint32Array;`,
    `  hasUV2?: boolean;`,
    `  uv2?: Float32Array;`,
    `}`,
  ];

  for (let mi = 0; mi < meshes.length; mi++) {
    const name = meshNames[mi];
    const safeName = name.replace(/^cciv_/, '');
    const prim = meshes[mi].primitives[0];
    const attrs = prim.attributes;
    const idxAcc = accessors[prim.indices];

    const fields = [];

    for (const [attrKey, accIdx] of Object.entries(attrs)) {
      const acc = accessors[accIdx];
      const bv = bufferViews[acc.bufferView];
      const TypedArray = COMP_TYPE[acc.componentType];
      const elemSize = COMP_SIZE[acc.componentType];
      const numComp = NUM_COMP[acc.type];
      const count = acc.count;
      const byteOffset = bv.byteOffset + (acc.byteOffset || 0);
      const byteLength = count * numComp * elemSize;

      const rawData = bin.slice(byteOffset, byteOffset + byteLength);
      const arr = new TypedArray(rawData.buffer, rawData.byteOffset, count * numComp);

      const aname = argName(attrKey);
      const arrName = `${safeName}_${aname}`;

      let tsType, formatter;
      if (TypedArray === Float32Array) {
        tsType = 'Float32Array';
        formatter = fmtFloat32;
      } else if (TypedArray === Uint16Array) {
        tsType = 'Uint16Array';
        formatter = fmtUint16;
      } else if (TypedArray === Uint32Array) {
        tsType = 'Uint32Array';
        formatter = fmtUint32;
      } else {
        throw new Error(`Unsupported component type: ${acc.componentType}`);
      }

      const jsContent = `// ${name} ${attrKey}: ${count}×${numComp} ${TypedArray.name}\n` +
        `export const ${arrName} = new ${tsType}([\n  ${formatter(arr)}\n]);\n`;

      writeFileSync(join(OUT_DIR, `${arrName}.js`), jsContent);
      console.log(`  Generated ${arrName}.js (${byteLength} bytes → ~${Math.round(byteLength * 1.4)} source)`);

      fields.push({ fieldName: aname, arrName });
    }

    // Indices
    const idxBv = bufferViews[idxAcc.bufferView];
    const idxTyped = COMP_TYPE[idxAcc.componentType];
    const idxElemSize = COMP_SIZE[idxAcc.componentType];
    const idxByteOffset = idxBv.byteOffset + (idxAcc.byteOffset || 0);
    const idxCount = idxAcc.count;
    const idxByteLength = idxCount * idxElemSize;
    const idxRaw = bin.slice(idxByteOffset, idxByteOffset + idxByteLength);
    const idxArr = new idxTyped(idxRaw.buffer, idxRaw.byteOffset, idxCount);

    const idxName = `${safeName}_idx`;
    let idxTsType, idxFormatter;
    if (idxTyped === Uint16Array) { idxTsType = 'Uint16Array'; idxFormatter = fmtUint16; }
    else if (idxTyped === Uint32Array) { idxTsType = 'Uint32Array'; idxFormatter = fmtUint32; }

    const idxContent = `// ${name} indices: ${idxCount}\n` +
      `export const ${idxName} = new ${idxTsType}([\n  ${idxFormatter(idxArr)}\n]);\n`;
    writeFileSync(join(OUT_DIR, `${idxName}.js`), idxContent);
    console.log(`  Generated ${idxName}.js (${idxByteLength} bytes → ~${Math.round(idxByteLength * 1.4)} source)`);

    // Add to index
    for (const f of fields) {
      indexTsLines.push(`import { ${f.arrName} } from './${f.arrName}.js';`);
    }
    indexTsLines.push(`import { ${idxName} } from './${idxName}.js';`);
    indexTsLines.push(`export const ${safeName}: MeshData = {`);
    for (const f of fields) indexTsLines.push(`  ${f.fieldName}: ${f.arrName},`);
    indexTsLines.push(`  indices: ${idxName},`);
    const hasUV2 = fields.some(f => f.fieldName === 'uv2');
    if (hasUV2) indexTsLines.push(`  hasUV2: true,`);
    indexTsLines.push(`};`);
    indexTsLines.push(``);
  }

  // Model info
  indexTsLines.push(`export const MODEL_INFO = {`);
  indexTsLines.push(`  name: 'cciv',`);
  indexTsLines.push(`  source: 'https://polyhaven.com/a/cciv',`);
  indexTsLines.push(`  license: 'CC0',`);
  indexTsLines.push(`  polyCount: ${Object.values(meshNames).reduce((s, n, i) => s + accessors[meshes[i].primitives[0].indices].count / 3, 0)},`);
  indexTsLines.push(`};`);

  // Build function
  indexTsLines.push(`
import * as THREE from 'three';

export function buildPinnaceGeometry(name: string): THREE.BufferGeometry {
  const data: MeshData = {
    ${Object.keys(meshNames).map((n, i) => {
      const safe = meshNames[i];
      return `'${safe}': ${safe}`;
    }).join(',\n    ')}
  }[name] as MeshData;
  if (!data) throw new Error('Unknown cciv mesh: ' + name);

  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.BufferAttribute(data.pos, 3));
  g.setAttribute('normal', new THREE.BufferAttribute(data.nml, 3));
  g.setAttribute('uv', new THREE.BufferAttribute(data.uv, 2));
  if (data.hasUV2 && data.uv2) {
    g.setAttribute('uv2', new THREE.BufferAttribute(data.uv2, 2));
  }
  g.setIndex(new THREE.BufferAttribute(data.indices, 1));
  return g;
}
`);

  writeFileSync(join(OUT_DIR, 'index.ts'), indexTsLines.join('\n'));
  console.log(`\nGenerated index.ts`);
  console.log(`\nDone! Files in ${OUT_DIR}`);
}

main();
